default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: experience_keroku_development

test:
  <<: *default
  database: experience_keroku_test

production:
  <<: *default
  database: experience_keroku_production
  username: experience_keroku
  password: <%= ENV["EXPERIENCE_KEROKU_DATABASE_PASSWORD"] %>
